/* 자동 생성: 영양 수치 = USDA FoodData Central(SR Legacy, 100g 생것), 이미지 = Wikipedia 대표 이미지(Wikimedia). 재생성: scratchpad/gen.ps1 */
const REF = {
    "rice":  {
                 "img":  "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0a/20201102.Hengnan.Hybrid_rice_Sanyou-1.6.jpg/330px-20201102.Hengnan.Hybrid_rice_Sanyou-1.6.jpg",
                 "wikiPage":  "https://en.wikipedia.org/wiki/Rice",
                 "wikiTitle":  "Rice",
                 "fdcId":  168877,
                 "fdcDesc":  "Rice, white, long-grain, regular, raw, enriched",
                 "fdcUrl":  "https://fdc.nal.usda.gov/food-details/168877/nutrients",
                 "n":  {
                           "fat":  0.66,
                           "carb":  80,
                           "kcal":  365,
                           "ca":  28,
                           "k":  115,
                           "zn":  1.09,
                           "protein":  7.13,
                           "vc":  0,
                           "fiber":  1.3,
                           "fe":  4.31,
                           "na":  5,
                           "folate":  387,
                           "vara":  0,
                           "sugar":  0.12
                       },
                 "proxy":  "쌀 건조(조리 전) 기준입니다. 죽·미음은 물을 넣어 묽어지므로 수치가 훨씬 낮아져요."
             },
    "oat":  {
                "img":  "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f0/AvenaSativa3.jpg/330px-AvenaSativa3.jpg",
                "wikiPage":  "https://en.wikipedia.org/wiki/Oat",
                "wikiTitle":  "Oat",
                "fdcId":  173904,
                "fdcDesc":  "Cereals, oats, regular and quick, not fortified, dry",
                "fdcUrl":  "https://fdc.nal.usda.gov/food-details/173904/nutrients",
                "n":  {
                          "kcal":  379,
                          "protein":  13.2,
                          "fat":  6.52,
                          "carb":  67.7,
                          "fiber":  10.1,
                          "ca":  52,
                          "fe":  4.25,
                          "k":  362,
                          "na":  6,
                          "zn":  3.64,
                          "vc":  0,
                          "folate":  32,
                          "vara":  0,
                          "sugar":  0.99
                      },
                "proxy":  "무가당 오트밀(건조) 기준입니다. 조리 후에는 수분 때문에 수치가 낮아져요."
            },
    "pumpkin":  {
                    "img":  "https://upload.wikimedia.org/wikipedia/commons/0/07/Kabocha.jpg",
                    "wikiPage":  "https://en.wikipedia.org/wiki/Kabocha",
                    "wikiTitle":  "Kabocha",
                    "fdcId":  169295,
                    "fdcDesc":  "Squash, winter, butternut, raw",
                    "fdcUrl":  "https://fdc.nal.usda.gov/food-details/169295/nutrients",
                    "n":  {
                              "fiber":  2,
                              "carb":  11.7,
                              "kcal":  45,
                              "vara":  532,
                              "folate":  27,
                              "ca":  48,
                              "k":  352,
                              "zn":  0.15,
                              "fat":  0.1,
                              "protein":  1,
                              "fe":  0.7,
                              "na":  4,
                              "vc":  21,
                              "sugar":  2.2
                          },
                    "proxy":  "단호박(kabocha) 대신 같은 박과 겨울호박인 USDA \u0027butternut squash\u0027 수치를 대체 사용했어요."
                },
    "zucchini":  {
                     "img":  "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/92/CSA-Striped-Zucchini.jpg/330px-CSA-Striped-Zucchini.jpg",
                     "wikiPage":  "https://en.wikipedia.org/wiki/Zucchini",
                     "wikiTitle":  "Zucchini",
                     "fdcId":  169291,
                     "fdcDesc":  "Squash, summer, zucchini, includes skin, raw",
                     "fdcUrl":  "https://fdc.nal.usda.gov/food-details/169291/nutrients",
                     "n":  {
                               "folate":  24,
                               "ca":  16,
                               "k":  261,
                               "zn":  0.32,
                               "fat":  0.32,
                               "carb":  3.11,
                               "kcal":  17,
                               "fiber":  1,
                               "fe":  0.37,
                               "na":  8,
                               "protein":  1.21,
                               "vc":  17.9,
                               "vara":  10,
                               "sugar":  2.5
                           }
                 },
    "sweetpotato":  {
                        "img":  "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/58/Ipomoea_batatas_006.JPG/330px-Ipomoea_batatas_006.JPG",
                        "wikiPage":  "https://en.wikipedia.org/wiki/Sweet_potato",
                        "wikiTitle":  "Sweet potato",
                        "fdcId":  168482,
                        "fdcDesc":  "Sweet potato, raw, unprepared (Includes foods for USDA\u0027s Food Distribution Program)",
                        "fdcUrl":  "https://fdc.nal.usda.gov/food-details/168482/nutrients",
                        "n":  {
                                  "kcal":  86,
                                  "protein":  1.57,
                                  "fat":  0.05,
                                  "carb":  20.1,
                                  "fiber":  3,
                                  "ca":  30,
                                  "fe":  0.61,
                                  "k":  337,
                                  "na":  55,
                                  "zn":  0.3,
                                  "vc":  2.4,
                                  "folate":  11,
                                  "vara":  709,
                                  "sugar":  4.18
                              }
                    },
    "potato":  {
                   "img":  "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ab/Patates.jpg/330px-Patates.jpg",
                   "wikiPage":  "https://en.wikipedia.org/wiki/Potato",
                   "wikiTitle":  "Potato",
                   "fdcId":  170026,
                   "fdcDesc":  "Potatoes, flesh and skin, raw",
                   "fdcUrl":  "https://fdc.nal.usda.gov/food-details/170026/nutrients",
                   "n":  {
                             "fat":  0.09,
                             "ca":  12,
                             "kcal":  77,
                             "vara":  0,
                             "vc":  19.7,
                             "na":  6,
                             "protein":  2.05,
                             "fiber":  2.1,
                             "fe":  0.81,
                             "folate":  15,
                             "carb":  17.5,
                             "k":  425,
                             "zn":  0.3,
                             "sugar":  0.82
                         }
               },
    "broccoli":  {
                     "img":  "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/03/Broccoli_and_cross_section_edit.jpg/330px-Broccoli_and_cross_section_edit.jpg",
                     "wikiPage":  "https://en.wikipedia.org/wiki/Broccoli",
                     "wikiTitle":  "Broccoli",
                     "fdcId":  170379,
                     "fdcDesc":  "Broccoli, raw",
                     "fdcUrl":  "https://fdc.nal.usda.gov/food-details/170379/nutrients",
                     "n":  {
                               "carb":  6.64,
                               "kcal":  34,
                               "fat":  0.37,
                               "ca":  47,
                               "k":  316,
                               "zn":  0.41,
                               "protein":  2.82,
                               "fiber":  2.6,
                               "fe":  0.73,
                               "na":  33,
                               "vc":  89.2,
                               "folate":  63,
                               "vara":  31,
                               "sugar":  1.7
                           }
                 },
    "carrot":  {
                   "img":  "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a2/Vegetable-Carrot-Bundle-wStalks.jpg/330px-Vegetable-Carrot-Bundle-wStalks.jpg",
                   "wikiPage":  "https://en.wikipedia.org/wiki/Carrot",
                   "wikiTitle":  "Carrot",
                   "fdcId":  170393,
                   "fdcDesc":  "Carrots, raw",
                   "fdcUrl":  "https://fdc.nal.usda.gov/food-details/170393/nutrients",
                   "n":  {
                             "fe":  0.3,
                             "na":  69,
                             "vc":  5.9,
                             "protein":  0.93,
                             "fat":  0.24,
                             "ca":  33,
                             "k":  320,
                             "zn":  0.24,
                             "carb":  9.58,
                             "kcal":  41,
                             "folate":  19,
                             "vara":  835,
                             "fiber":  2.8,
                             "sugar":  4.74
                         }
               },
    "cabbage":  {
                    "img":  "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6f/Cabbage_and_cross_section_on_white.jpg/330px-Cabbage_and_cross_section_on_white.jpg",
                    "wikiPage":  "https://en.wikipedia.org/wiki/Cabbage",
                    "wikiTitle":  "Cabbage",
                    "fdcId":  169975,
                    "fdcDesc":  "Cabbage, raw",
                    "fdcUrl":  "https://fdc.nal.usda.gov/food-details/169975/nutrients",
                    "n":  {
                              "fat":  0.1,
                              "carb":  5.8,
                              "kcal":  25,
                              "ca":  40,
                              "k":  170,
                              "zn":  0.18,
                              "folate":  43,
                              "vc":  36.6,
                              "vara":  5,
                              "protein":  1.28,
                              "fiber":  2.5,
                              "fe":  0.47,
                              "na":  18,
                              "sugar":  3.2
                          }
                },
    "spinach":  {
                    "img":  "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/37/Spinacia_oleracea_Spinazie_bloeiend.jpg/330px-Spinacia_oleracea_Spinazie_bloeiend.jpg",
                    "wikiPage":  "https://en.wikipedia.org/wiki/Spinach",
                    "wikiTitle":  "Spinach",
                    "fdcId":  168462,
                    "fdcDesc":  "Spinach, raw",
                    "fdcUrl":  "https://fdc.nal.usda.gov/food-details/168462/nutrients",
                    "n":  {
                              "ca":  99,
                              "k":  558,
                              "zn":  0.53,
                              "protein":  2.86,
                              "fe":  2.71,
                              "na":  79,
                              "vc":  28.1,
                              "fiber":  2.2,
                              "folate":  194,
                              "fat":  0.39,
                              "carb":  3.63,
                              "kcal":  23,
                              "vara":  469,
                              "sugar":  0.42
                          }
                },
    "radish":  {
                   "img":  "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/23/Different_kinds_of_White_Radish.png/330px-Different_kinds_of_White_Radish.png",
                   "wikiPage":  "https://en.wikipedia.org/wiki/Daikon",
                   "wikiTitle":  "Daikon",
                   "fdcId":  168451,
                   "fdcDesc":  "Radishes, oriental, raw",
                   "fdcUrl":  "https://fdc.nal.usda.gov/food-details/168451/nutrients",
                   "n":  {
                             "kcal":  18,
                             "protein":  0.6,
                             "fat":  0.1,
                             "carb":  4.1,
                             "fiber":  1.6,
                             "ca":  27,
                             "fe":  0.4,
                             "k":  227,
                             "na":  21,
                             "zn":  0.15,
                             "vc":  22,
                             "folate":  28,
                             "vara":  0,
                             "sugar":  2.5
                         },
                   "proxy":  "USDA의 동양 무(oriental radish) 항목입니다."
               },
    "apple":  {
                  "img":  "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a6/Pink_lady_and_cross_section.jpg/330px-Pink_lady_and_cross_section.jpg",
                  "wikiPage":  "https://en.wikipedia.org/wiki/Apple",
                  "wikiTitle":  "Apple",
                  "fdcId":  171688,
                  "fdcDesc":  "Apples, raw, with skin (Includes foods for USDA\u0027s Food Distribution Program)",
                  "fdcUrl":  "https://fdc.nal.usda.gov/food-details/171688/nutrients",
                  "n":  {
                            "kcal":  52,
                            "protein":  0.26,
                            "fat":  0.17,
                            "carb":  13.8,
                            "fiber":  2.4,
                            "ca":  6,
                            "fe":  0.12,
                            "k":  107,
                            "na":  1,
                            "zn":  0.04,
                            "vc":  4.6,
                            "folate":  3,
                            "vara":  3,
                            "sugar":  10.4
                        }
              },
    "pear":  {
                 "img":  "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cf/Pears.jpg/330px-Pears.jpg",
                 "wikiPage":  "https://en.wikipedia.org/wiki/Pear",
                 "wikiTitle":  "Pear",
                 "fdcId":  169118,
                 "fdcDesc":  "Pears, raw",
                 "fdcUrl":  "https://fdc.nal.usda.gov/food-details/169118/nutrients",
                 "n":  {
                           "kcal":  57,
                           "protein":  0.36,
                           "fat":  0.14,
                           "carb":  15.2,
                           "fiber":  3.1,
                           "ca":  9,
                           "fe":  0.18,
                           "k":  116,
                           "na":  1,
                           "zn":  0.1,
                           "vc":  4.3,
                           "folate":  7,
                           "vara":  1,
                           "sugar":  9.75
                       }
             },
    "banana":  {
                   "img":  "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/de/Bananavarieties.jpg/330px-Bananavarieties.jpg",
                   "wikiPage":  "https://en.wikipedia.org/wiki/Banana",
                   "wikiTitle":  "Banana",
                   "fdcId":  173944,
                   "fdcDesc":  "Bananas, raw",
                   "fdcUrl":  "https://fdc.nal.usda.gov/food-details/173944/nutrients",
                   "n":  {
                             "kcal":  89,
                             "protein":  1.09,
                             "fat":  0.33,
                             "carb":  22.8,
                             "fiber":  2.6,
                             "ca":  5,
                             "fe":  0.26,
                             "k":  358,
                             "na":  1,
                             "zn":  0.15,
                             "vc":  8.7,
                             "folate":  20,
                             "vara":  3,
                             "sugar":  12.2
                         }
               },
    "beef":  {
                 "img":  "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/60/Standing-rib-roast.jpg/330px-Standing-rib-roast.jpg",
                 "wikiPage":  "https://en.wikipedia.org/wiki/Beef",
                 "wikiTitle":  "Beef",
                 "fdcId":  173125,
                 "fdcDesc":  "Beef, round, tip round, roast, separable lean only, trimmed to 0\" fat, all grades, raw",
                 "fdcUrl":  "https://fdc.nal.usda.gov/food-details/173125/nutrients",
                 "n":  {
                           "kcal":  126,
                           "protein":  21.1,
                           "fat":  3.95,
                           "carb":  0,
                           "fiber":  0,
                           "ca":  18,
                           "fe":  1.77,
                           "k":  323,
                           "na":  54,
                           "zn":  3.89,
                           "vc":  0,
                           "folate":  12,
                           "vara":  0,
                           "sugar":  0
                       },
                 "proxy":  "지방을 제거한 우둔(round tip roast) 살코기 기준입니다."
             },
    "chicken":  {
                    "img":  "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/57/Chickens_in_market.jpg/330px-Chickens_in_market.jpg",
                    "wikiPage":  "https://en.wikipedia.org/wiki/Chicken_as_food",
                    "wikiTitle":  "Chicken as food",
                    "fdcId":  171077,
                    "fdcDesc":  "Chicken, broiler or fryers, breast, skinless, boneless, meat only, raw",
                    "fdcUrl":  "https://fdc.nal.usda.gov/food-details/171077/nutrients",
                    "n":  {
                              "kcal":  120,
                              "protein":  22.5,
                              "fat":  2.62,
                              "carb":  0,
                              "fiber":  0,
                              "ca":  5,
                              "fe":  0.37,
                              "k":  334,
                              "na":  45,
                              "zn":  0.68,
                              "vc":  0,
                              "folate":  9,
                              "vara":  9,
                              "sugar":  0
                          }
                },
    "tofu":  {
                 "img":  "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/03/Japanese_SilkyTofu_%28Kinugoshi_Tofu%29.JPG/330px-Japanese_SilkyTofu_%28Kinugoshi_Tofu%29.JPG",
                 "wikiPage":  "https://en.wikipedia.org/wiki/Tofu",
                 "wikiTitle":  "Tofu",
                 "fdcId":  172476,
                 "fdcDesc":  "Tofu, raw, regular, prepared with calcium sulfate",
                 "fdcUrl":  "https://fdc.nal.usda.gov/food-details/172476/nutrients",
                 "n":  {
                           "kcal":  76,
                           "protein":  8.08,
                           "fat":  4.78,
                           "carb":  1.87,
                           "fiber":  0.3,
                           "ca":  350,
                           "fe":  5.36,
                           "k":  121,
                           "na":  7,
                           "zn":  0.8,
                           "vc":  0.1,
                           "folate":  15,
                           "sugar":  0.62
                       },
                 "proxy":  "칼슘 응고제(황산칼슘)를 쓴 일반 두부 기준입니다."
             },
    "eggyolk":  {
                    "img":  "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3f/Huevo_frito.jpg/330px-Huevo_frito.jpg",
                    "wikiPage":  "https://en.wikipedia.org/wiki/Eggs_as_food",
                    "wikiTitle":  "Eggs as food",
                    "fdcId":  172184,
                    "fdcDesc":  "Egg, yolk, raw, fresh",
                    "fdcUrl":  "https://fdc.nal.usda.gov/food-details/172184/nutrients",
                    "n":  {
                              "kcal":  322,
                              "protein":  15.9,
                              "fat":  26.5,
                              "carb":  3.59,
                              "fiber":  0,
                              "ca":  129,
                              "fe":  2.73,
                              "k":  109,
                              "na":  48,
                              "zn":  2.3,
                              "vc":  0,
                              "folate":  146,
                              "vara":  381,
                              "sugar":  0.56
                          }
                },
    "whitefish":  {
                      "img":  "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/77/Atlantic_Cod%2C_Atlantischer_Kabeljau_%28Gadus_morhua%29.jpg/330px-Atlantic_Cod%2C_Atlantischer_Kabeljau_%28Gadus_morhua%29.jpg",
                      "wikiPage":  "https://en.wikipedia.org/wiki/Atlantic_cod",
                      "wikiTitle":  "Atlantic cod",
                      "fdcId":  171955,
                      "fdcDesc":  "Fish, cod, Atlantic, raw",
                      "fdcUrl":  "https://fdc.nal.usda.gov/food-details/171955/nutrients",
                      "n":  {
                                "kcal":  82,
                                "protein":  17.8,
                                "fat":  0.67,
                                "carb":  0,
                                "fiber":  0,
                                "ca":  16,
                                "fe":  0.38,
                                "k":  413,
                                "na":  54,
                                "zn":  0.45,
                                "vc":  1,
                                "folate":  7,
                                "vara":  12,
                                "sugar":  0
                            }
                  },
    "yogurt":  {
                   "img":  "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b8/Joghurt.jpg/330px-Joghurt.jpg",
                   "wikiPage":  "https://en.wikipedia.org/wiki/Yogurt",
                   "wikiTitle":  "Yogurt",
                   "fdcId":  171284,
                   "fdcDesc":  "Yogurt, plain, whole milk",
                   "fdcUrl":  "https://fdc.nal.usda.gov/food-details/171284/nutrients",
                   "n":  {
                             "kcal":  61,
                             "protein":  3.47,
                             "fat":  3.25,
                             "carb":  4.66,
                             "fiber":  0,
                             "ca":  121,
                             "fe":  0.05,
                             "k":  155,
                             "na":  46,
                             "zn":  0.59,
                             "vc":  0.5,
                             "folate":  7,
                             "vara":  27,
                             "sugar":  4.66
                         },
                   "proxy":  "플레인 전지 요거트 기준입니다."
               }
};
